/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLog {
  'id' : string,
  'action' : string,
  'userId' : UserId,
  'timestamp' : Timestamp,
  'ipAddress' : string,
}
export type ExternalBlob = Uint8Array;
export interface FileRecord {
  'id' : string,
  'owner' : UserId,
  'blob' : ExternalBlob,
  'size' : bigint,
  'fileType' : string,
  'filename' : string,
  'uploadDate' : Timestamp,
  'riskLevel' : RiskLevel,
}
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'adminAssignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'adminGetAllActivityLogs' : ActorMethod<[], Array<ActivityLog>>,
  'adminListAllFiles' : ActorMethod<[], Array<FileRecord>>,
  'adminListUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteFile' : ActorMethod<[string], undefined>,
  'getAdminStats' : ActorMethod<
    [],
    {
      'totalFiles' : bigint,
      'threatLevel' : string,
      'highRiskFiles' : bigint,
      'recentAlerts' : bigint,
      'totalUsers' : bigint,
    }
  >,
  'getCallerRole' : ActorMethod<[], UserRole>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFile' : ActorMethod<[string], [] | [FileRecord]>,
  'getMyActivityLogs' : ActorMethod<[], Array<ActivityLog>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyFiles' : ActorMethod<[], Array<FileRecord>>,
  'logActivity' : ActorMethod<[string, string], undefined>,
  'registerUser' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'uploadFile' : ActorMethod<
    [string, bigint, string, ExternalBlob],
    FileRecord
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];